services:
  wordpress-service:
    build: ./wordpress
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_NAME: ${POSTGRES_DB}
      WORDPRESS_DB_USER: ${POSTGRES_USER}
      WORDPRESS_DB_PASSWORD: ${POSTGRES_PASSWORD}
      WORDPRESS_DB_HOST: postgres-service
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app_network
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:${POSTGRES_VERSION:-13}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  wordpress_data:
  postgres_data:

networks:
  app_network:
